name: "Tree"

exports: "mootools-tree.js"

web: "[cpojer.net](http://cpojer.net)"

description: "A set of components to sort and/or collapse/expand a tree."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Christoph Pojer](http://cpojer.net/)"

author: "cpojer"
authors: "[Christoph Pojer](http://cpojer.net)"

sources:
    - "Source/Tree.js"
    - "Source/Collapse.js"
    - "Source/Collapse.Cookie.js"
